config/routes.rb
SchoolScheduleCreator::Application.routes.draw do
  root to: 'welcomes#welcome'

  post '/', to: "session#login"

  get  '/courses', to: "courses#new_and_edit",      as: :courses
  post '/courses', to: "courses#create_and_update", as: :create_and_update_courses

  get  '/teachers', to: "teachers#new_and_edit",      as: :teachers
  post '/teachers', to: "teachers#create_and_update", as: :create_and_update_teachers

  get  '/rooms', to: "rooms#new_and_edit",      as: :rooms
  post '/rooms', to: "rooms#create_and_update", as: :create_and_update_rooms

  get '/school/new',     to: "schools#new",    as: :new_school
  get '/school/edit',    to: "schools#edit",   as: :edit_school
  get '/school',         to: "schools#show",   as: :school
  get '/schools',        to: "schools#index",  as: :schools
  post '/school/create', to: "schools#create", as: :create_school
  post '/school/update', to: "schools#update", as: :update_school

  get 'not_ready_yet', to: 'welcomes#not_ready_yet'
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
	def welcome
	end

	def not_ready_yet
	end
end

app/views/welcomes/not_ready_yet.html.erb
<html>
<head>
	<title>WIP Site</title>
</head>
<body style="background-color:gray;">
  <h1 style="text-align:center; margin:auto;width:50%;">Site Not Ready Yet</h1>

  <%= audio_tag "corona.mp3", autoplay: true%>

  <br><br>

  <%= image_tag "http://www.onlythebeat.com/wp-content/uploads/2013/11/morgan-page-dancing-gif.gif", size: "400x400", id: "gorilla", style: "position:relative; left:20%;width:60%"%>

</body>
</html>



<!--
<html><html lang=en><head><meta charset=UTF-8><title>Cultures Back</title></head><body><iframe width=100% height=1000px src=http://www.youtube.com/embed/T9RFb8xXZlk?autoplay=1 frameborder=0 allowfullscreen></iframe></body></html> -->
<!--
http://www.onlythebeat.com/wp-content/uploads/2013/11/morgan-page-dancing-gif.gif -->

app/views/welcomes/welcome.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<%= link_to "New School", new_school_path, id: "new_school" %>

<%= form_tag root_url, id: "login_form" do  %>

  <%=  label_tag :name, "School Name"%>
  <%=  text_field_tag 'name' %>
  <br>
  <%=  label_tag :password %>
  <br>
  <%=  password_field_tag 'password' %>
  <br>
  <%= button_tag "login", id: "login_id",name: "Login" %>

<% end %>