config/routes.rb
SchoolScheduleCreator::Application.routes.draw do
  root to: 'welcomes#welcome'

  post '/', to: "session#login"

  get  '/courses', to: "courses#new_and_edit",      as: :courses
  post '/courses', to: "courses#create_and_update", as: :create_and_update_courses

  get  '/teachers', to: "teachers#new_and_edit",      as: :teachers
  post '/teachers', to: "teachers#create_and_update", as: :create_and_update_teachers

  get  '/rooms', to: "rooms#new_and_edit",      as: :rooms
  post '/rooms', to: "rooms#create_and_update", as: :create_and_update_rooms

  get '/school/new',     to: "schools#new",    as: :new_school
  get '/school/edit',    to: "schools#edit",   as: :edit_school
  get '/school',         to: "schools#show",   as: :school
  get '/schools',        to: "schools#index",  as: :schools
  post '/school/create', to: "schools#create", as: :create_school
  post '/school/update', to: "schools#update", as: :update_school

  get 'not_ready_yet', to: 'welcomes#not_ready_yet'
end

app/models/school.rb
class School < ActiveRecord::Base
  attr_accessible :name, :bio, :location

  validates :name,     presence: true, uniqueness: true
  validates :bio,      presence: true
  validates :location, presence: true, uniqueness: true
  validates :password, presence: true

  has_many :teachers
  has_many :courses_pools, dependent: :destroy
  has_many :rooms,         dependent: :destroy

  has_one  :time_open, class_name: "Timespan",
                       as: :timeable,
                       dependent: :destroy

  has_secure_password

  def deleteNoLongerNeededCourses(courses)
    course_numbers_arr = []
    courses.values.each do |course|
      course_numbers_arr << course['course_number']
    end

    self.courses_pools.where("courses_pools.course_number NOT IN (?)", course_numbers_arr).destroy_all
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
	def edit
    @school = current_school
  end

  def new
  	session[:school_id] = nil if session[:school_id]

    @school = School.new
  end

	def show
		@school = current_school
	end

	def create
		new_school = School.new(params[:school])

		if params[:password] != params[:password_confirmation] # error passwords not same
			@school = new_school
			flash[:notice] = "School Name Exists Already"
			flash[:color]  = "Error"
			redirect_to courses_path

    elsif School.find_by_name(params[:name])  # error school exists already
			@school = new_school
			flash[:notice] = "School Name Exists Already"
			flash[:color]  = "Error"
			redirect_to courses

		else
    	new_school.password = params[:school][:password]
    	new_school.password_confirmation = params[:school][:password_confirmation]
    	new_school.save
    	session[:school_id] = new_school.id

		  redirect_to courses_path
		end
	end

	def update
    s = School.find_by_name(params[:name])

		if params[:password] == "" || params[:password_confirmation] == "" # No password entered
			@school = School.new(params[:school])

			flash[:notice] =  "Must enter password AND password confirmation"
			flash[:color]  = "Error"
			redirect_to edit_school_course(current_school)

		elsif params[:password] != params[:password_confirmation] # error passwords not same
			flash[:notice] = "Please Re-enter Password"
			flash[:color]  = "Error"
			redirect_to new_course_path

		elsif s && s.id != current_school.id  # if another school has the name already
			@school = School.new(params[:school])

			flash[:notice] = "School Name Exists Already"
			flash[:color]  = "Error"
			redirect_to edit_course_path

		else
			current_school.update_attributes(params[:school])
    	current_school.password = params[:school][:password]
    	current_school.password_confirmation = params[:school][:password_confirmation]
    	current_school.save
		  redirect_to school_path
		end
	end
end

app/views/schools/_school_form.html.erb
<!-- <%# <% if flash[:notice] %>
  <p><%#= flash[:notice] %></p>
<%# end %>


<%#= form_for @school,  url: next_path do |f| %>
  School Name: <%#= f.text_field :name, value:(@school.name || "School_#{School.count + 1}") %>
  <br>
  <br>
  Password: <%#= f.text_field :password, value:(@school.new_record? ? 1234 : "") %>
  <br>
  <br>
  Password Confirmation: <%#= f.text_field :password_confirmation, value:(@school.new_record? ? 1234 : "") %>
  <br>
  <br>
  Location: <%#= f.text_field :location, value:(@school.location || "#{School.count + 1}.#{rand(888)} #{School.count + 1}.#{rand(888)}") %>
  <br>
  <br>
  Fun Fact About Your School: <%#= f.text_field :bio, value:(@school.name || "School_#{School.count + 1}") %>
  <br>
  <br>
  <%= f.submit button_name %>
<%# end %> %> -->

app/views/schools/edit.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>


<%= form_for @school,  url: update_school_path, method: :post do |f| %>
  School Name: <%= f.text_field :name, value:@school.name  %>
  <br>
  <br>
  Password: <%= f.text_field :password %>
  <br>
  <br>
  Password Confirmation: <%= f.text_field :password_confirmation %>
  <br>
  <br>
  Location: <%= f.text_field :location, value: @school.location %>
  <br>
  <br>
  Fun Fact About Your School: <%= f.text_field :bio, value: @school.name %>
  <br>
  <br>
  <%= f.submit "update" %>
<% end %>

app/views/schools/new.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>


<%= form_for @school, url: create_school_path do |f| %>
  School Name: <%= f.text_field :name, value:(@school.name || "School_#{School.count + 1}") %>
  <br>
  <br>
  Password: <%= f.text_field :password, value:(@school.new_record? ? 1234 : "") %>
  <br>
  <br>
  Password Confirmation: <%= f.text_field :password_confirmation, value:(@school.new_record? ? 1234 : "") %>
  <br>
  <br>
  Location: <%= f.text_field :location, value:(@school.location || "#{School.count + 1}.#{rand(888)} #{School.count + 1}.#{rand(888)}") %>
  <br>
  <br>
  Fun Fact About Your School: <%= f.text_field :bio, value:(@school.name || "School_#{School.count + 1}") %>
  <br>
  <br>
  <%= f.submit "next" %>
<% end %>

app/views/schools/show.html.erb
School : <%= @school.name %>
<br>
Location : <%= @school.location %>
<br>
<br>
<br>
Previous schedules or create new schedules